DROP TABLE IF EXISTS "clients";

CREATE TABLE "clients" (
    "id" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "name" VARCHAR(255),
    "gender" VARCHAR(255),
    "age" INT,
    "dni" VARCHAR(255),
    "address" VARCHAR(255),
    "phone" VARCHAR(255),
    "password" VARCHAR(255),
    "is_active" BOOLEAN,
    "created_at" TIMESTAMP NULL,
    "updated_at" TIMESTAMP NULL,
    "deleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "deleted_at" TIMESTAMP NULL
);


-- Insertar datos en la tabla de clientes
INSERT INTO "clients" (
     "name", "gender", "age", "dni", "address", "phone", "password", "is_active", "created_at", "deleted"
) VALUES
( 'Jose Lema', 'M', 30, '100000001', 'Otavalo sn y principal', '098254785', '1234', true, NOW(), 'false'),
( 'Marianela Montalvo', 'F', 28, '100000002', 'Amazonas y NNUU', '097548965', '5678', true, NOW(), 'false'),
( 'Juan Osorio', 'M', 32, '100000003', '13 junio y Equinoccial', '098874587', '1245', true, NOW(), 'false');
-- Sincronizar el contador de autoincremento para la tabla de clientes
-- Esto asegura que el próximo ID generado sea mayor que el último ID insertado.
ALTER TABLE "clients" ALTER COLUMN "id" RESTART WITH (SELECT MAX("id") + 1 FROM "clients");


DROP TABLE IF EXISTS "movements";
DROP TABLE IF EXISTS "accounts";

CREATE TABLE "accounts" (
  "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id"        BIGINT             NOT NULL,
  "account_number"   VARCHAR(50)        NOT NULL UNIQUE,
  "account_type"     VARCHAR(20)        NOT NULL,
  "initial_balance"  DECIMAL(19,2)      NOT NULL,
  "is_active"        BOOLEAN            NOT NULL DEFAULT TRUE,
  "created_at"       TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"       TIMESTAMP NULL,
  "deleted"          BOOLEAN            NOT NULL DEFAULT FALSE,
  "deleted_at"       TIMESTAMP NULL,
  CONSTRAINT "chk_account_type" CHECK ("account_type" IN ('SAVINGS','CURRENT'))
);

CREATE TABLE "movements" (
  "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount"         DECIMAL(19,2)   NOT NULL,
  "balance"        DECIMAL(19,2)   NOT NULL,
  "date"           TIMESTAMP       NOT NULL,
  "movement_type"           VARCHAR(20)     NOT NULL,  -- <— texto, no TINYINT
  "account_id"     BIGINT          NOT NULL,
  "created_at"     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"     TIMESTAMP NULL,
  "deleted"        BOOLEAN         NOT NULL DEFAULT FALSE,
  "deleted_at"     TIMESTAMP NULL,
  CONSTRAINT "chk_movement_type" CHECK ("movement_type" IN ('INITIAL_DEPOSIT','DEPOSIT','WITHDRAWAL')),
  CONSTRAINT "fk_movements_account"
      FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE
);


-- ============ ACCOUNTS ============
INSERT INTO "accounts" (
  "id","client_id","account_number","account_type",
  "initial_balance","is_active","created_at","updated_at","deleted","deleted_at"
) VALUES
(1,1,'478758','SAVINGS',2000.00,TRUE,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(2,2,'225487','CURRENT', 100.00,TRUE,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(3,3,'495878','SAVINGS',   0.00,TRUE,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(4,2,'496825','SAVINGS', 540.00,TRUE,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(5,1,'585545','CURRENT',1000.00,TRUE,CURRENT_TIMESTAMP,NULL,FALSE,NULL);

-- ============ MOVEMENTS ============
-- Movimientos de apertura (INITIAL_DEPOSIT)
INSERT INTO "movements" (
  "id","amount","balance","date","movement_type","account_id",
  "created_at","updated_at","deleted","deleted_at"
) VALUES
(1, 2000.00, 2000.00, TIMESTAMP '2025-08-03 10:05:00','INITIAL_DEPOSIT', 1,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(2,  100.00,  100.00, TIMESTAMP '2022-02-08 10:05:00','INITIAL_DEPOSIT', 2,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(3,    0.00,    0.00, TIMESTAMP '2025-08-03 10:05:00','INITIAL_DEPOSIT', 3,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(4,  540.00,  540.00, TIMESTAMP '2025-02-10 10:05:00','INITIAL_DEPOSIT', 4,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(5, 1000.00, 1000.00, TIMESTAMP '2025-08-03 10:05:00','INITIAL_DEPOSIT', 5,CURRENT_TIMESTAMP,NULL,FALSE,NULL),

-- Movimientos posteriores
(6,  575.00, 1425.00, TIMESTAMP '2025-08-03 10:00:00','WITHDRAWAL',      1,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(7,  600.00,  700.00, TIMESTAMP '2022-02-08 10:05:00','DEPOSIT',         2,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(8,  150.00,  150.00, TIMESTAMP '2025-08-03 10:10:00','DEPOSIT',         3,CURRENT_TIMESTAMP,NULL,FALSE,NULL),
(9,  540.00,    0.00, TIMESTAMP '2025-02-10 10:15:00','WITHDRAWAL',      4,CURRENT_TIMESTAMP,NULL,FALSE,NULL);

-- Reset IDs
ALTER TABLE "accounts"  ALTER COLUMN "id" RESTART WITH 6;
ALTER TABLE "movements" ALTER COLUMN "id" RESTART WITH 10;