version: '3.8'

services:
  client-service:
    build: ./client-service        # carpeta donde está tu microservicio de cliente
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    restart: always

  account-service:
    build: ./account-service       # carpeta donde está account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:accounts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_PORT=8081
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      # 👇 aquí sobreescribes la URL del client-service
      - CLIENT_SERVICE_URL=http://client-service:8080
    depends_on:
      - client-service
    restart: always