DROP TABLE IF EXISTS "movements";
DROP TABLE IF EXISTS "accounts";

CREATE TABLE "accounts" (
  "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id"        BIGINT             NOT NULL,
  "account_number"   VARCHAR(50)        NOT NULL UNIQUE,
  "account_type"     VARCHAR(20)        NOT NULL,
  "initial_balance"  DECIMAL(19,2)      NOT NULL,
  "is_active"        BOOLEAN            NOT NULL DEFAULT TRUE,
  "created_at"       TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"       TIMESTAMP NULL,
  "deleted"          BOOLEAN            NOT NULL DEFAULT FALSE,
  "deleted_at"       TIMESTAMP NULL,
  CONSTRAINT "chk_account_type" CHECK ("account_type" IN ('SAVINGS','CURRENT'))
);

CREATE TABLE "movements" (
  "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount"         DECIMAL(19,2)   NOT NULL,
  "balance"        DECIMAL(19,2)   NOT NULL,
  "date"           TIMESTAMP       NOT NULL,
  "movement_type"           VARCHAR(20)     NOT NULL,  -- <— texto, no TINYINT
  "account_id"     BIGINT          NOT NULL,
  "created_at"     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"     TIMESTAMP NULL,
  "deleted"        BOOLEAN         NOT NULL DEFAULT FALSE,
  "deleted_at"     TIMESTAMP NULL,
  CONSTRAINT "chk_movement_type" CHECK ("movement_type" IN ('INITIAL_DEPOSIT','DEPOSIT','WITHDRAWAL')),
  CONSTRAINT "fk_movements_account"
      FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE
);